name: Build Python Project

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-local-path: "~/uv-cache"
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Lint
        continue-on-error: true
        run: uv run flake8

  # build-python:
  #   name: Build Python project
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #         cache-local-path: "~/uv-cache"
  #         cache-dependency-glob: "uv.lock"

  #     - name: Set up Python
  #       uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
  #       with:
  #         python-version-file: "pyproject.toml"

  #     - name: Install Dependencies
  #       run: uv sync

  #     - name: Unit Test
  #       run: uv run pytest -m 'not integration and not ui_tests and not real_data'