version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"

  # Shared package dependencies
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps(shared)"
      include: "scope"

  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
