name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

# This workflow runs on PRs to main for testing and validation
# Does NOT deploy - deployment happens via deploy.yml after PR merge

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.13'

jobs:
  # Frontend CI
  frontend-ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --include-workspace-root

      - name: Build shared package
        run: npm run build --workspace=shared

      - name: Lint frontend
        continue-on-error: true
        run: npm run lint --workspace=frontend

      - name: Build frontend
        run: npm run build --workspace=frontend

  # Backend CI
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Lint with Ruff
        continue-on-error: true
        run: ruff check .

      - name: Test FastAPI startup
        run: |
          python -c "from app.main import app; print('FastAPI app loads successfully')"
